stages:
  - test
  - build
  - deploy

# 代码检查阶段
lint:
  stage: test
  before_script:
    - git config --global url."https://oauth2:${ACCESS_TOKEN}@gitlab.quantanalysis.cn".insteadOf "https://gitlab.quantanalysis.cn"
    - git clone https://oauth2:${ACCESS_TOKEN}@gitlab.quantanalysis.cn/chatroom/chatroom.git .
    - git remote -v
  script:
    - npm install
    - npm run lint # 假设你使用的是 JavaScript 相关项目
  except:
    - tags # 排除在 tags 上运行

# 构建前端项目（只有 lint 通过且是 master 或 v 开头的分支时触发）
build_frontend:
  stage: build
  before_script:
    - git config --global url."https://oauth2:${ACCESS_TOKEN}@gitlab.quantanalysis.cn".insteadOf "https://gitlab.quantanalysis.cn"
  script:
    - npm install
    - npm run build # 打包项目，生成静态文件
  artifacts:
    paths:
      - chatroom/ # 假设打包后的文件存放在 chatroom 目录
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
  dependencies:
    - lint # 确保 build 只在 lint 通过时触发

# 部署到服务器或静态托管服务
deploy_prod:
  stage: deploy
  script:
    - scp chatroom.tar.gz root@47.120.40.71:/encrypt/$CI_COMMIT_REF_NAME/ # 发送打包文件到对应分支的目录
    - ssh root@47.120.40.71 "mkdir -p /encrypt/$CI_COMMIT_REF_NAME && tar -xzf /encrypt/$CI_COMMIT_REF_NAME/chatroom.tar.gz -C /encrypt/$CI_COMMIT_REF_NAME/" # 在服务器上解压文件到对应分支的目录
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
  dependencies:
    - build_frontend
